{
    "track_id": "QtkmrK4W",
    "prompt": "Unknown ERROR->ContentTypeError",
    "time": "2021-08-05 17:23:56",
    "content": "Traceback (most recent call last):\n  File \"D:\\feiBot\\bot\\.\\src\\exceptions.py\", line 103, in _track_error\n    raise exception\n  File \"c:\\users\\hasee\\appdata\\local\\programs\\python\\python39\\lib\\site-packages\\nonebot\\message.py\", line 154, in _run_matcher\n    await matcher.run(bot, event, state)\n  File \"c:\\users\\hasee\\appdata\\local\\programs\\python\\python39\\lib\\site-packages\\nonebot\\matcher.py\", line 544, in run\n    await handler(self, bot, event, state_)\n  File \"c:\\users\\hasee\\appdata\\local\\programs\\python\\python39\\lib\\site-packages\\nonebot\\handler.py\", line 81, in __call__\n    await self.func(\n  File \"D:\\feiBot\\bot\\src/plugins\\setu\\__init__.py\", line 55, in _tag_setu\n    setu, title, p_id, is_ok = await Setu().tag_setu(tag)\n  File \"D:\\feiBot\\bot\\src/plugins\\setu\\data_source.py\", line 46, in tag_setu\n    data: dict = await res.json()\n  File \"D:\\feiBot\\bot\\.\\src\\utils\\request.py\", line 45, in json\n    return await self.raw_response.json()\n  File \"c:\\users\\hasee\\appdata\\local\\programs\\python\\python39\\lib\\site-packages\\aiohttp\\client_reqrep.py\", line 1097, in json\n    raise ContentTypeError(\naiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html', url=URL('https://api.lolicon.app/setu/v2?tag=%E8%80%BD%E7%BE%8E')\n"
}