{
    "track_id": "Wbr9cj2R",
    "prompt": "Unknown ERROR->ActionFailed",
    "time": "2021-08-09 09:52:16",
    "content": "Traceback (most recent call last):\n  File \"D:\\feiBot\\bot\\.\\src\\exceptions.py\", line 103, in _track_error\n    raise exception\n  File \"c:\\users\\hasee\\appdata\\local\\programs\\python\\python39\\lib\\site-packages\\nonebot\\message.py\", line 154, in _run_matcher\n    await matcher.run(bot, event, state)\n  File \"c:\\users\\hasee\\appdata\\local\\programs\\python\\python39\\lib\\site-packages\\nonebot\\matcher.py\", line 544, in run\n    await handler(self, bot, event, state_)\n  File \"c:\\users\\hasee\\appdata\\local\\programs\\python\\python39\\lib\\site-packages\\nonebot\\handler.py\", line 81, in __call__\n    await self.func(\n  File \"D:\\feiBot\\bot\\src/plugins\\raid\\__init__.py\", line 51, in _wave_tuan\n    await kaituan.finish(wv)\n  File \"c:\\users\\hasee\\appdata\\local\\programs\\python\\python39\\lib\\site-packages\\nonebot\\matcher.py\", line 479, in finish\n    await bot.send(event=event, message=message, **kwargs)\n  File \"c:\\users\\hasee\\appdata\\local\\programs\\python\\python39\\lib\\site-packages\\nonebot\\adapters\\cqhttp\\bot.py\", line 456, in send\n    return await self.send_msg(**params)\n  File \"c:\\users\\hasee\\appdata\\local\\programs\\python\\python39\\lib\\site-packages\\nonebot\\adapters\\cqhttp\\bot.py\", line 400, in call_api\n    return await super().call_api(api, **data)\n  File \"c:\\users\\hasee\\appdata\\local\\programs\\python\\python39\\lib\\site-packages\\nonebot\\adapters\\_base.py\", line 199, in call_api\n    raise exception\n  File \"c:\\users\\hasee\\appdata\\local\\programs\\python\\python39\\lib\\site-packages\\nonebot\\adapters\\_base.py\", line 182, in call_api\n    result = await self._call_api(api, **data)\n  File \"c:\\users\\hasee\\appdata\\local\\programs\\python\\python39\\lib\\site-packages\\nonebot\\adapters\\cqhttp\\bot.py\", line 347, in _call_api\n    return _handle_api_result(await ResultStore.fetch(\n  File \"c:\\users\\hasee\\appdata\\local\\programs\\python\\python39\\lib\\site-packages\\nonebot\\adapters\\cqhttp\\bot.py\", line 188, in _handle_api_result\n    raise ActionFailed(**result)\nnonebot.adapters.cqhttp.exception.ActionFailed: <ActionFailed data=None, echo={'seq': 1}, msg=SEND_MSG_API_ERROR, retcode=100, status=failed, wording=\u8bf7\u53c2\u8003 go-cqhttp \u7aef\u8f93\u51fa>\n"
}