{
    "track_id": "xAzKDLJM",
    "prompt": "Unknown ERROR->NetworkError",
    "time": "2021-08-04 09:52:03",
    "content": "Traceback (most recent call last):\n  File \"D:\\feiBot\\bot\\.\\src\\exceptions.py\", line 103, in _track_error\n    raise exception\n  File \"c:\\users\\hasee\\appdata\\local\\programs\\python\\python39\\lib\\site-packages\\nonebot\\message.py\", line 154, in _run_matcher\n    await matcher.run(bot, event, state)\n  File \"c:\\users\\hasee\\appdata\\local\\programs\\python\\python39\\lib\\site-packages\\nonebot\\matcher.py\", line 544, in run\n    await handler(self, bot, event, state_)\n  File \"c:\\users\\hasee\\appdata\\local\\programs\\python\\python39\\lib\\site-packages\\nonebot\\handler.py\", line 81, in __call__\n    await self.func(\n  File \"D:\\feiBot\\bot\\src/plugins\\query\\__init__.py\", line 30, in _random_setu\n    msg_1 = await bot.send(event, Message(setu))\n  File \"c:\\users\\hasee\\appdata\\local\\programs\\python\\python39\\lib\\site-packages\\nonebot\\adapters\\cqhttp\\bot.py\", line 456, in send\n    return await self.send_msg(**params)\n  File \"c:\\users\\hasee\\appdata\\local\\programs\\python\\python39\\lib\\site-packages\\nonebot\\adapters\\cqhttp\\bot.py\", line 400, in call_api\n    return await super().call_api(api, **data)\n  File \"c:\\users\\hasee\\appdata\\local\\programs\\python\\python39\\lib\\site-packages\\nonebot\\adapters\\_base.py\", line 199, in call_api\n    raise exception\n  File \"c:\\users\\hasee\\appdata\\local\\programs\\python\\python39\\lib\\site-packages\\nonebot\\adapters\\_base.py\", line 182, in call_api\n    result = await self._call_api(api, **data)\n  File \"c:\\users\\hasee\\appdata\\local\\programs\\python\\python39\\lib\\site-packages\\nonebot\\adapters\\cqhttp\\bot.py\", line 347, in _call_api\n    return _handle_api_result(await ResultStore.fetch(\n  File \"c:\\users\\hasee\\appdata\\local\\programs\\python\\python39\\lib\\site-packages\\nonebot\\adapters\\cqhttp\\bot.py\", line 217, in fetch\n    raise NetworkError(\"WebSocket API call timeout\") from None\nnonebot.adapters.cqhttp.exception.NetworkError: <NetWorkError message=WebSocket API call timeout>\n"
}